name: Lint and Format

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8

    - name: Auto-format with autopep8
      run: |
        find ./invERT -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} \;

    - name: Commit changes if any
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Auto-format code with autopep8"
          git push origin HEAD:master  # Specify branch to push to
        fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
