# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if python -c "import torch; print(torch.cuda.is_available())" | grep True; then
          echo "GPU detected, installing PyTorch with CUDA..."
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
        else
          echo "No GPU detected, keeping CPU-only PyTorch..."
        fi
    - uses: actions/checkout@v2
    - name: autopep8
      uses: peter-evans/autopep8@v2
      with:
        args: --recursive --in-place --aggressive --aggressive .
    - name: Commit autopep8 changes
      if: steps.autopep8.outputs.exit-code == 2
      run: |
        git commit -am "Automated autopep8 fixes"
        git push
      
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Set PYTHONPATH to the root invERT directory
      run: |
        echo "PYTHONPATH=$(pwd)/invERT" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        cd invERT
        pytest
