name: Test Application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH to the root invERT directory
      run: |
        echo "PYTHONPATH=$(pwd)/invERT" >> $GITHUB_ENV

    - name: Run tests with pytest
      run: |
        cd invERT
        pytest --maxfail=5 --disable-warnings
